export const FAQ_SCREEN_KEYS = {
  DASHBOARD: "DASHBOARD",
  DOCUMENTS: "DOCUMENTS",
  EMPLOYEES: "EMPLOYEES",
  USERS: "USERS",
  COMPANIES: "COMPANIES",
  TIME_RECORDS: "TIME_RECORDS",
  VACATION: "VACATION",
  TIME_OFF: "TIME_OFF",
  AUDIT: "AUDIT",
  PRIVACY: "PRIVACY",
} as const;

export type FaqScreenKey = (typeof FAQ_SCREEN_KEYS)[keyof typeof FAQ_SCREEN_KEYS];
